// Bharatiya Nyaya Sanhita (BNS) - IPC Comparison Data

export interface BNSSection {
    id: number;
    ipcSection: string;
    bnsSection: string;
    offense: string;
    keyDifference: string;
    category: "Body" | "Women" | "Property" | "Public Order" | "New BNS";
    type: "IPC→BNS" | "New BNS" | "IPC Removed";
}

export const bnsSections: BNSSection[] = [
    // Murder & Attempt to Murder
    {
        id: 1,
        ipcSection: "IPC 302",
        bnsSection: "BNS 103",
        offense: "Murder",
        keyDifference: "Punishment remains same - death or life imprisonment",
        category: "Body",
        type: "IPC→BNS",
    },
    {
        id: 2,
        ipcSection: "IPC 307",
        bnsSection: "BNS 109",
        offense: "Attempt to Murder",
        keyDifference: "Provisions consolidated, punishment structure unchanged",
        category: "Body",
        type: "IPC→BNS",
    },

    // Sexual Offenses
    {
        id: 3,
        ipcSection: "IPC 375",
        bnsSection: "BNS 63",
        offense: "Rape",
        keyDifference: "Enhanced minimum sentence, clearer definition of consent",
        category: "Women",
        type: "IPC→BNS",
    },
    {
        id: 4,
        ipcSection: "IPC 376",
        bnsSection: "BNS 64",
        offense: "Punishment for Rape",
        keyDifference: "Mandatory minimum 10 years, up to life imprisonment or death",
        category: "Women",
        type: "IPC→BNS",
    },
    {
        id: 5,
        ipcSection: "IPC 354",
        bnsSection: "BNS 74",
        offense: "Assault with intent to outrage modesty",
        keyDifference: "Enhanced punishment - up to 5 years and fine",
        category: "Women",
        type: "IPC→BNS",
    },
    {
        id: 6,
        ipcSection: "IPC 354A",
        bnsSection: "BNS 75",
        offense: "Sexual Harassment",
        keyDifference: "Broader definition, workplace harassment provisions strengthened",
        category: "Women",
        type: "IPC→BNS",
    },
    {
        id: 7,
        ipcSection: "IPC 354B",
        bnsSection: "BNS 76",
        offense: "Assault with intent to disrobe",
        keyDifference: "Minimum 3 years, up to 7 years imprisonment",
        category: "Women",
        type: "IPC→BNS",
    },

    // Cruelty by Husband
    {
        id: 8,
        ipcSection: "IPC 498A",
        bnsSection: "BNS 84",
        offense: "Cruelty by husband or relatives",
        keyDifference: "Definition expanded, punishment remains up to 3 years",
        category: "Women",
        type: "IPC→BNS",
    },
    {
        id: 9,
        ipcSection: "IPC 304B",
        bnsSection: "BNS 80",
        offense: "Dowry Death",
        keyDifference: "Minimum 7 years, up to life imprisonment",
        category: "Women",
        type: "IPC→BNS",
    },

    // Hurt & Grievous Hurt
    {
        id: 10,
        ipcSection: "IPC 319",
        bnsSection: "BNS 114",
        offense: "Hurt",
        keyDifference: "Definition clarified, punishment up to 1 year or fine up to ₹10,000",
        category: "Body",
        type: "IPC→BNS",
    },
    {
        id: 11,
        ipcSection: "IPC 320",
        bnsSection: "BNS 115",
        offense: "Grievous Hurt",
        keyDifference: "Eight types of grievous hurt clearly defined",
        category: "Body",
        type: "IPC→BNS",
    },
    {
        id: 12,
        ipcSection: "IPC 325",
        bnsSection: "BNS 117",
        offense: "Voluntarily causing grievous hurt",
        keyDifference: "Enhanced punishment - up to 7 years and fine",
        category: "Body",
        type: "IPC→BNS",
    },
    {
        id: 13,
        ipcSection: "IPC 326",
        bnsSection: "BNS 118",
        offense: "Causing grievous hurt by dangerous weapon",
        keyDifference: "Life imprisonment or up to 10 years and fine",
        category: "Body",
        type: "IPC→BNS",
    },
    {
        id: 14,
        ipcSection: "IPC 326A",
        bnsSection: "BNS 124",
        offense: "Acid Attack",
        keyDifference: "Minimum 10 years, up to life imprisonment and fine",
        category: "Body",
        type: "IPC→BNS",
    },

    // Kidnapping & Trafficking
    {
        id: 15,
        ipcSection: "IPC 359",
        bnsSection: "BNS 135",
        offense: "Kidnapping",
        keyDifference: "Definition refined, clearer distinction from abduction",
        category: "Body",
        type: "IPC→BNS",
    },
    {
        id: 16,
        ipcSection: "IPC 363",
        bnsSection: "BNS 137",
        offense: "Kidnapping for ransom",
        keyDifference: "Enhanced punishment - up to 10 years and fine",
        category: "Body",
        type: "IPC→BNS",
    },
    {
        id: 17,
        ipcSection: "IPC 366",
        bnsSection: "BNS 138",
        offense: "Kidnapping woman to compel marriage",
        keyDifference: "Punishment up to 10 years and fine",
        category: "Women",
        type: "IPC→BNS",
    },
    {
        id: 18,
        ipcSection: "IPC 370",
        bnsSection: "BNS 142",
        offense: "Trafficking of persons",
        keyDifference: "Comprehensive definition, minimum 7 years up to life imprisonment",
        category: "Body",
        type: "IPC→BNS",
    },

    // Theft, Robbery, Dacoity
    {
        id: 19,
        ipcSection: "IPC 378",
        bnsSection: "BNS 303",
        offense: "Theft",
        keyDifference: "Definition unchanged, punishment up to 3 years or fine or both",
        category: "Property",
        type: "IPC→BNS",
    },
    {
        id: 20,
        ipcSection: "IPC 379",
        bnsSection: "BNS 303",
        offense: "Punishment for Theft",
        keyDifference: "Consolidated with definition, up to 3 years or fine or both",
        category: "Property",
        type: "IPC→BNS",
    },
    {
        id: 21,
        ipcSection: "IPC 380",
        bnsSection: "BNS 305",
        offense: "Theft in dwelling house",
        keyDifference: "Enhanced punishment - up to 7 years and fine",
        category: "Property",
        type: "IPC→BNS",
    },
    {
        id: 22,
        ipcSection: "IPC 390",
        bnsSection: "BNS 309",
        offense: "Robbery",
        keyDifference: "Definition includes theft + violence/threat, up to 10 years",
        category: "Property",
        type: "IPC→BNS",
    },
    {
        id: 23,
        ipcSection: "IPC 391",
        bnsSection: "BNS 310",
        offense: "Dacoity",
        keyDifference: "5 or more persons committing robbery, life imprisonment or 10 years",
        category: "Property",
        type: "IPC→BNS",
    },
    {
        id: 24,
        ipcSection: "IPC 392",
        bnsSection: "BNS 309",
        offense: "Punishment for Robbery",
        keyDifference: "Up to 10 years rigorous imprisonment and fine",
        category: "Property",
        type: "IPC→BNS",
    },

    // Cheating & Forgery
    {
        id: 25,
        ipcSection: "IPC 415",
        bnsSection: "BNS 316",
        offense: "Cheating",
        keyDifference: "Definition refined for digital era, punishment up to 3 years or fine",
        category: "Property",
        type: "IPC→BNS",
    },
    {
        id: 26,
        ipcSection: "IPC 420",
        bnsSection: "BNS 318",
        offense: "Cheating and dishonestly inducing delivery of property",
        keyDifference: "Enhanced punishment - up to 7 years and fine",
        category: "Property",
        type: "IPC→BNS",
    },
    {
        id: 27,
        ipcSection: "IPC 463",
        bnsSection: "BNS 336",
        offense: "Forgery",
        keyDifference: "Includes digital/electronic forgery, up to 2 years or fine or both",
        category: "Property",
        type: "IPC→BNS",
    },
    {
        id: 28,
        ipcSection: "IPC 465",
        bnsSection: "BNS 338",
        offense: "Punishment for Forgery",
        keyDifference: "Up to 2 years or fine or both",
        category: "Property",
        type: "IPC→BNS",
    },
    {
        id: 29,
        ipcSection: "IPC 467",
        bnsSection: "BNS 340",
        offense: "Forgery of valuable security",
        keyDifference: "Life imprisonment or up to 10 years and fine",
        category: "Property",
        type: "IPC→BNS",
    },

    // Criminal Breach of Trust
    {
        id: 30,
        ipcSection: "IPC 405",
        bnsSection: "BNS 316",
        offense: "Criminal Breach of Trust",
        keyDifference: "Definition modernized, punishment up to 3 years or fine or both",
        category: "Property",
        type: "IPC→BNS",
    },
    {
        id: 31,
        ipcSection: "IPC 406",
        bnsSection: "BNS 317",
        offense: "Punishment for Criminal Breach of Trust",
        keyDifference: "Up to 3 years or fine or both",
        category: "Property",
        type: "IPC→BNS",
    },
    {
        id: 32,
        ipcSection: "IPC 409",
        bnsSection: "BNS 318",
        offense: "Criminal Breach of Trust by public servant",
        keyDifference: "Life imprisonment or up to 10 years and fine",
        category: "Property",
        type: "IPC→BNS",
    },

    // Defamation
    {
        id: 33,
        ipcSection: "IPC 499",
        bnsSection: "BNS 356",
        offense: "Defamation",
        keyDifference: "Includes cyber defamation, oral/written/signs/visible representation",
        category: "Public Order",
        type: "IPC→BNS",
    },
    {
        id: 34,
        ipcSection: "IPC 500",
        bnsSection: "BNS 356",
        offense: "Punishment for Defamation",
        keyDifference: "Up to 2 years or fine or both",
        category: "Public Order",
        type: "IPC→BNS",
    },

    // Criminal Intimidation
    {
        id: 35,
        ipcSection: "IPC 503",
        bnsSection: "BNS 351",
        offense: "Criminal Intimidation",
        keyDifference: "Includes cyber intimidation, up to 2 years or fine or both",
        category: "Public Order",
        type: "IPC→BNS",
    },
    {
        id: 36,
        ipcSection: "IPC 506",
        bnsSection: "BNS 352",
        offense: "Punishment for Criminal Intimidation",
        keyDifference: "Enhanced punishment for threats of death/grievous hurt - up to 7 years",
        category: "Public Order",
        type: "IPC→BNS",
    },

    // Unlawful Assembly & Rioting
    {
        id: 37,
        ipcSection: "IPC 141",
        bnsSection: "BNS 189",
        offense: "Unlawful Assembly",
        keyDifference: "Definition retained, 5 or more persons with common object",
        category: "Public Order",
        type: "IPC→BNS",
    },
    {
        id: 38,
        ipcSection: "IPC 143",
        bnsSection: "BNS 191",
        offense: "Punishment for Unlawful Assembly",
        keyDifference: "Up to 6 months or fine or both",
        category: "Public Order",
        type: "IPC→BNS",
    },
    {
        id: 39,
        ipcSection: "IPC 147",
        bnsSection: "BNS 192",
        offense: "Rioting",
        keyDifference: "Use of force or violence by unlawful assembly, up to 2 years or fine or both",
        category: "Public Order",
        type: "IPC→BNS",
    },
    {
        id: 40,
        ipcSection: "IPC 148",
        bnsSection: "BNS 193",
        offense: "Rioting with deadly weapon",
        keyDifference: "Enhanced punishment - up to 3 years or fine or both",
        category: "Public Order",
        type: "IPC→BNS",
    },

    // Sedition - REMOVED
    {
        id: 41,
        ipcSection: "IPC 124A",
        bnsSection: "N/A (Removed)",
        offense: "Sedition",
        keyDifference: "REMOVED - Colonial-era sedition law abolished, replaced with narrower provisions",
        category: "Public Order",
        type: "IPC Removed",
    },

    // New BNS Offenses
    {
        id: 42,
        ipcSection: "N/A",
        bnsSection: "BNS 111",
        offense: "Organized Crime",
        keyDifference: "NEW - Targets organized criminal syndicates, minimum 5 years up to life imprisonment",
        category: "New BNS",
        type: "New BNS",
    },
    {
        id: 43,
        ipcSection: "N/A",
        bnsSection: "BNS 103(2)",
        offense: "Mob Lynching",
        keyDifference: "NEW - Specific provision for mob killing, death penalty or life imprisonment",
        category: "New BNS",
        type: "New BNS",
    },
    {
        id: 44,
        ipcSection: "Various IPC sections",
        bnsSection: "BNS 113",
        offense: "Acts endangering sovereignty/unity",
        keyDifference: "Replaces sedition with specific acts against sovereignty, narrower scope",
        category: "New BNS",
        type: "New BNS",
    },
    {
        id: 45,
        ipcSection: "N/A",
        bnsSection: "BNS 69",
        offense: "Gang Rape of minor under 16",
        keyDifference: "NEW - Specific provision, punishment is death or life imprisonment",
        category: "Women",
        type: "New BNS",
    },
    {
        id: 46,
        ipcSection: "IPC 376AB",
        bnsSection: "BNS 70",
        offense: "Rape of woman under 18",
        keyDifference: "Minimum 20 years, up to life imprisonment or death",
        category: "Women",
        type: "IPC→BNS",
    },

    // Additional Property Crimes
    {
        id: 47,
        ipcSection: "IPC 381",
        bnsSection: "BNS 306",
        offense: "Theft by clerk or servant",
        keyDifference: "Enhanced punishment - up to 7 years and fine",
        category: "Property",
        type: "IPC→BNS",
    },
    {
        id: 48,
        ipcSection: "IPC 382",
        bnsSection: "BNS 307",
        offense: "Theft after preparation for hurt/death",
        keyDifference: "Up to 10 years rigorous imprisonment and fine",
        category: "Property",
        type: "IPC→BNS",
    },

    // Offense against Public Servants
    {
        id: 49,
        ipcSection: "IPC 353",
        bnsSection: "BNS 132",
        offense: "Assault to deter public servant",
        keyDifference: "Enhanced punishment - up to 2 years or fine or both",
        category: "Public Order",
        type: "IPC→BNS",
    },
    {
        id: 50,
        ipcSection: "IPC 186",
        bnsSection: "BNS 221",
        offense: "Obstructing public servant",
        keyDifference: "Up to 3 months or fine or both",
        category: "Public Order",
        type: "IPC→BNS",
    },

    // Culpable Homicide
    {
        id: 51,
        ipcSection: "IPC 299",
        bnsSection: "BNS 100",
        offense: "Culpable Homicide",
        keyDifference: "Definition retained with minor clarifications",
        category: "Body",
        type: "IPC→BNS",
    },
    {
        id: 52,
        ipcSection: "IPC 300",
        bnsSection: "BNS 101",
        offense: "Murder (Definition)",
        keyDifference: "Four categories of murder clearly defined",
        category: "Body",
        type: "IPC→BNS",
    },
    {
        id: 53,
        ipcSection: "IPC 304",
        bnsSection: "BNS 105",
        offense: "Culpable Homicide not amounting to murder",
        keyDifference: "Up to 10 years or fine or both (Part I), 10 years (Part II)",
        category: "Body",
        type: "IPC→BNS",
    },

    // Abetment
    {
        id: 54,
        ipcSection: "IPC 107",
        bnsSection: "BNS 47",
        offense: "Abetment",
        keyDifference: "Definition includes digital/electronic abetment",
        category: "Public Order",
        type: "IPC→BNS",
    },
    {
        id: 55,
        ipcSection: "IPC 109",
        bnsSection: "BNS 49",
        offense: "Punishment for Abetment",
        keyDifference: "Same punishment as offense abetted if act committed",
        category: "Public Order",
        type: "IPC→BNS",
    },
];
